title: Happy Narwhal
description: Modern Software Development

url: "https://happynarwhal.rocks"
permalink: /blog/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  pages:
    output: true
    permalink: "/:name"
  portfolio:
    output: true
    permalink: "/portfolio/:path"
  games:
    output: true
    permalink: "/games/:path"

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "blog"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
      permalink: "/:name"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "games"
      permalink: "/:name"

markdown: kramdown
highlighter: rouge
paginate: 10
sass:
  style: :compressed
